name: SimpleTrains
version: 1.1.0
main: com.andrestube.simpletrains.SimpleTrains
api-version: '1.20'
authors: [AndresTube]
description: A simple fast-travel rail system using activation blocks.

commands:
  train:
    description: Main command for SimpleTrains plugin.
    usage: /<command> <subcommand>
    aliases: [sttrain]
    permission: simpletrains.use
    permission-message: You do not have permission to use SimpleTrains commands.

permissions:
  simpletrains.use:
    description: Allows use of SimpleTrains commands.
    default: true
  simpletrains.admin:
    description: Allows access to admin commands for SimpleTrains.
    default: op
  simpletrains.create:
    description: Allows players to create new train stations.
    default: op